Hamburger-menu
UmerZia/Portfolio-Microverse pull request #11
Opened 2022-07-21 23:10 UTC by UmerZia

### In this brach I:
- add a hamburger menu
- add move to selected area

2022-07-21 23:43 UTC, 1GORDON requested changes
##
## Hi @UmerZia ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Descriptive Pull Request ✔️
- Linters are passing ✔️
- Professional Readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 23:43 UTC, 1GORDON commented on index.html
> +              ><img class="social" src="images/Linkdin.svg" alt="Linkdin"
Great job @UmerZia 🤝

- [ ] You may kindly make sure these social icons don't appear on top of the mobile menu as you scroll down through the page.
![overlap 2](https://user-images.githubusercontent.com/63917725/180332475-10d4dec4-7b71-4b5d-b29f-27200cc80deb.PNG)

2022-07-21 23:43 UTC, 1GORDON commented on index.html
>          <p>
Great design @UmerZia 🤝

- [ ] You kindly make this diamond not to appear as you scroll down through the mobile menu
![overlap1](https://user-images.githubusercontent.com/63917725/180332374-2f6645f9-6c16-448d-9602-f4630713cb36.PNG)

2022-07-22 08:39 UTC, UmerZia commented on index.html
>          <p>
I fixed this issue.

2022-07-22 08:42 UTC, UmerZia commented
I fixed the mention issue by increasing z-index value of navbar.

2022-07-22 09:10 UTC, Nemwel-Boniface approved these changes
## Hello @UmerZia               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the changes requested by the previous reviewer good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 14:57 UTC, merged