Media query Screen 768px
UmerZia/Portfolio-Microverse pull request #5
Opened 2022-07-07 21:12 UTC by UmerZia

### In this branch I:

- Add mediaQuerys according to 768px wide screen.
- Made my webpage fully responsive.

2022-07-07 21:46 UTC, Lucas-Masaba requested changes
# Hello @UmerZia 👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Good-looking UI 🧹 
- Linter checks passing ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 21:46 UTC, Lucas-Masaba commented on index.html
>          <ul class="icon">
- [ ] Please increase the spacing between the paragraph and the icons as seen in the Figma template 👍 
### Your Implementation
![image](https://user-images.githubusercontent.com/45460192/177876092-4621f841-b2ce-43de-958f-af43967f5695.png)
### Figma 
![image](https://user-images.githubusercontent.com/45460192/177876150-1140e670-bc7b-44c5-9a2c-65119d7237fc.png)

2022-07-07 21:46 UTC, Lucas-Masaba commented on style.css
> +  }
- [ ] Please make this image larger as seen in the Figma template.
### Your Design
![image](https://user-images.githubusercontent.com/45460192/177876516-d2500647-1c55-4d7e-a6b4-45936564c85e.png)
### Figma template
![image](https://user-images.githubusercontent.com/45460192/177876615-2046b1c8-4da0-49be-8370-7b5776bb0b96.png)

2022-07-08 08:59 UTC, UmerZia commented on index.html
>          <ul class="icon">
I have applied the changes as per instructions.

2022-07-08 09:00 UTC, UmerZia commented on style.css
> +  }
I have increased the width % of the image.

2022-07-08 09:23 UTC, Kandy-Peter approved these changes
Hi @UmerZia,

### APPROVED 🟢 

Great implementation of all the requirements in this milestone. 👏
Your web app looks really fantastic. 🎉 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

##  Optional suggestion

- [ ] OPTIONAL: It would be better if you enlarge your section's height. Their heights are too small. You can increase to make them take, each one, the all-screen size on non-scroll.

 
# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 09:40 UTC, merged